### ISSUE TITLE
Requirements? botocore, boto3, and awscli downgrades?

### ISSUE THREAD

**Issue by jimweller** [venth/aws-adfs#75]
We're looking at using aws-adfs @ REI.

As it stands, aws-adfs forces downgrades of awscli, botocore, and boto3. The downgrade is a problem for us.

I think this is unnecessary. I just made a change in setup.py to >= and it all works fine in a venv. Is there a reason for the older versions that I am missing?  Thoughts on changing it to just allow for current releases?

setup.py
```
install_requires = [
    'lxml',
    'click',
    # defined by the specific awscli version - see its setup.py
    'botocore>=1.8.26',
    # corresponding to botocore awscli version
    'awscli>=1.14.22',
    # corresponding to botocore version
    'boto3>=1.5.12',
    'requests[security]',
    'configparser',
]
```

Here's my pip freeze

```
asn1crypto==0.24.0
-e git+https://github.com/jimweller/aws-adfs.git@db327564144eed56342e4c9ce814dadeeedb7c77#egg=aws_adfs
awscli==1.14.46
boto3==1.5.36
botocore==1.8.50
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
click==6.7
colorama==0.3.7
configparser==3.5.0
cryptography==2.1.4
docutils==0.14
idna==2.6
jmespath==0.9.3
lxml==4.1.1
pyasn1==0.4.2
pycparser==2.18
pyOpenSSL==17.5.0
pypiwin32==220
python-dateutil==2.6.1
PyYAML==3.12
requests==2.18.4
requests-negotiate-sspi==0.3.4
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
urllib3==1.22
```

**Comment by venth** [comment]
The issue cause is versioning in aws-cli. Take a look on the fragment of setup.py from aws-cli project:
```
requires = ['botocore==1.9.0',
            'colorama>=0.2.5,<=0.3.7',
            'docutils>=0.10',
            'rsa>=3.1.2,<=3.5.0',
            's3transfer>=0.1.12,<0.2.0',
            'PyYAML>=3.10,<=3.12']
```
`aws-cli` requires specific version of `botocore` library and it looks that doesn't follow semver guide lines. Both this facts make hard to introduce version ranges for `awscli` and `boto3` relies on `botocore` library.

`aws-cli` dependency was introduced to provide aws command repetition (`awsr`) when temporary credentials were expired.

`greater or equals` was already used in the project and solved the issue till `botocore` is upgraded and `boto3` is upgraded and `awscli` isn't. Due to constant issue raising `greater or equals` was changed to requiring a strict version.

Till now I didn't find any elegant and satisfying solution. Perhaps the command repetition `awsr` has to be extracted to a separate project or there is a solution to build dependencies in runtime during installation.

For now perhaps I'll just upgrade versions to keep up with awscli, boto3 and botocore changes, what do you think?

**Comment by jimweller** [comment]
Thank you for the clear explanation. I understand now. Our use case (per the printenv PR) doesn't require refreshing tokens with awsr. And we're using the aws.exe from the AWS download (vs. the pip repo). So, removing the aws-cli dependencies seems logical on the surface. Or maybe approaching awsr w/ the assumption that the aws command is already in the PATH and shelling out to it instead of using the clidriver? I'm no expert, just thinking out loud.

**Comment by venth** [comment]
`awsr` is installed along with aws-adfs and relies on awscli. Providing shell scripts for each end every console among all OS'es looks like huge work.
I'll consider removal of awsr. In a meanwhile I'll upgrade dependencies.

**Comment by venth** [comment]
New version of boto3 and botocore along with removal of awsr released with version 0.8.0

**Comment by venth** [comment]
Can I close this one?

**Comment by jimweller** [comment]
Yes. Thank you!
