### ISSUE TITLE
Ability to add environment variables

### ISSUE THREAD

**Issue by holmesjr** [venth/aws-adfs#8]
It would be great to be able to populate the environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION` with a command line switch. This would make passing creds through to a Docker container easy, for example.

Eager to hear your thoughts.

**Comment by venth** [comment]
Passing secrets via environment variables is insecure. Having this in mind I follow slightly different approach based on mounting volumes. My docker containers operate in aws environment, they don't need any credentials to interact with aws api using boto, throposphere, sdk or cli thanks to a proper IAM role assigned to them. In case of local development I mount aws secrets on container's /var/secrets directory. During containers boostrap a bash script added to the entrypoint verifies if there are secrets there and in case of necessity copies changing ownership and files modes. As for local work is sufficient, not entirely convenient, because when credentials are expired I need to enter container and retrigger credentials copy process. Of course, if you use only root user in container then linking is sufficient. There is no need to copy, so in case of credentials expiration simple re authentication on server machine is sufficient. Other way is to assign the same uid and gid for a container user as the user that has access to secrets on your machine - but this is a trick. In order to achieve that you need to pass uid, gid and then on container bootstrap in a script attached to entrypoint play with filesystem and /etc/group - a lot of tricky work.
Please consider using the mounting approach, if it doesn't fit your usage scenario just describe the scenario, perhaps there is other way to achieve the success.

**Comment by holmesjr** [comment]
I suspected that might be the answer. I'll consider the mounting approach.

**Comment by venth** [comment]
May I close the issue? ;)

**Comment by holmesjr** [comment]
Sorry, yes, I'll do that now.
